import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className="bg-gradient-to-br from-[#001F3F] via-[#007F7F] to-[#FFD700] font-sans text-white dark:text-white dark:bg-black min-h-screen"
        style={{
          fontFamily: "Inter, Orbitron, sans-serif",
        }}
      >
        {children}
      </body>
    </html>
  );
}
